language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - MAGENTO_VERSION=1.7.0.2
  - MAGENTO_VERSION=1.8.1.0
  - MAGENTO_VERSION=1.9.0.1
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
before_script:
  - mysql -uroot -e "CREATE USER 'meanbee_core'@'localhost' IDENTIFIED BY 'meanbee_core';"
  - mysql -uroot -e "GRANT ALL ON meanbee_core.* TO 'meanbee_core'@'localhost';"
  - mysql -uroot -e "GRANT ALL ON meanbee_core_test.* TO 'meanbee_core'@'localhost';"
  - mysql -uroot -e "FLUSH PRIVILEGES;"
  - composer selfupdate
  - composer install --dev --no-interaction
  - wget http://www.phing.info/get/phing-latest.phar
  - mv phing-latest.phar phing.phar
  - chmod +x phing.phar
  - mkdir bin && cd bin && wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x bin/modman

script:
  - php phing.phar -Ddb.pass='meanbee_core' -Ddb.user='meanbee_core' -Ddb.name='meanbee_core' -Dmagento.version=$MAGENTO_VERSION test
